---
title: "Book Club Hosting Guide"
output: 
    github_document:
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This can help hosts of the book club events - especially useful if you rotate hosts, have multiple locations or online meetings. 

Hosts should also adhere to the Facilitator Guide.

### Welcoming

- Have one or two people at the entrance to welcome people in
- Ask people to write out a name label, if they so wish. Include pronouns (if you feel comfortable with this!)
- Let them know when we&#39;ll be starting (e.g. 6:30pm doors for 6:45pm start)

### Opening the Event

- Intro to DataKind UK and why we are interested in ethics
- Welcome from the sponsor (e.g. if being hosted at a company's meeting space)
- Reminder of the topic and materials
- Reminder of others: We are running the book club simultaneously with friends in Scotland and online
- Tell community this is a safe space:
  + to explore ideas and opinions.
  + Everyone should listen actively with a **generous and open mind**
  + do not interrupt or criticise others,
  + consciously aim to help everyone to speak for roughly equal time
  + If anyone feels uncomfortable at any time do speak with [**named responsible individual/s **]
  + Chatham House [rules](https://www.chathamhouse.org/chatham-house-rule)
- Ask people to get into groups of 6-8
- Point out the facilitators
- Ask people to put thoughts on Twitter [**your hashtag here**] but paraphrase what people say if needed, as it is Chatham House
- There&#39;ll be a break in the middle (go round and remind the groups of this at 7:30pm) and give option for people to move groups at this time - or any time if they want to!

### End

- Ask participants if anyone would like to write a blog about the book club around the questions discussed
- Let everyone know about the next book club
- No one location, always looking for hosts. if your organisation would like to host a bookclub - et us know
  + If you would like to facilitate
  + If you have ideas about future topics
- We will send out a feedback survey tomorrow.
- Thanks again to the sponsor