remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true
  collections: true
include:
  - README.md
title: Data Ethics and Society Reading Group