---
title: "Data Ethics Book Club in a Box"
output: 
    github_document:
    toc_float: TRUE
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

DataKind UK Data Ethics Book Club processes and materials

This is [DataKind UK](https://datakind.org.uk/)'s intro to setting up a data ethics book club. We started in 2019, with seven book club events. They were run every 6-8 weeks or so in London, Edinburgh and remotely.

There has been interest from others who would like to replicate (and, we hope, improve!), and we 

It's not just a books - we used books as well as journal articles, blogs, news stories, videos of talks and even poems.

The aims of the book club before starting were to: 

1. To foster discussions of ethics issues among our data science community, and later on, the wider data science community, that they can take back to their day jobs/careers; 
2. To educate and inform our community on ethical issues, to better enable them to support social change organisations; and 
3. To strengthen our community of data scientists, social change organisations, and data for good enthusiasts. 

## Structure
General processes for a book club are found in [Processes](/Processes).

* [What to think about for your book club](/Processes/What-you-need-for-your-book-club.md)
* [Sample Facilitator Guide](/Processes/Sample-Facilitator-Guide.md)
* [Sample Hosting Guide](/Processes/Sample-Hosting-Guide.md)
* [Sample Book Club FAQs](/Processes/Sample-Book-Club-FAQs.md) 

## Topics
These topics were run by DataKind UK during 2019. They may help others get started too!

1. [Impacts of Algorithms](/Topics and Materials/1.-Impacts-of-Algorithms.md)
2. [Facial Recognition](/Topics and Materials/2.-Facial-Recognition.md)
3. [Fairness in AI](/Topics and Materials/3.-Fairness-in-AI.md)
4. [Self-Driving Cars](/Topics and Materials/4.-Self-driving-Cars.md)
5. [AI and Gender](/Topics and Materials/5.-AI-and-Gender.md)
6. [AI and Financial Inclusion](/Topics and Materials/6.-AI-and-Financial-Inclusion.md)
7. [AI and Race](/Topics and Materials/7.-AI-and-Race.md)

## Materials
All materials used in the DataKind UK Data Ethics Book club are also provided: 

* [All materials](/Topics and Materials/All-Reading-Materials---2019.md)

## Suggestions or Changes?
Please do contribute to the repo via Github (there's a helpful guide to web-based changes [here](https://github.com/Data4Democracy/ethics-research) or use the git commandline if you prefer) or you can get in touch at <contact@datakind.org.uk> 

## Want to join in? 
The DataKind UK Data Ethics Book Club continues in 2020! Keep an eye out for local and remote events [here](https://www.eventbrite.co.uk/o/datakind-uk-4112514489) or [sign up](https://datakind.org.uk/) to get newsletters/join the #ethics Slack channel. 